### ISSUE TITLE
Exposure of personal information (ID, password) in the source code.

### ISSUE THREAD

**Issue by kim-do-hyeon** [clyde0813/Interpark-Ticketing#2]
**The password is checked by looking at the ID,** which is the personal information in the source code.
It would be better to check and correct the problem.

I think you should also delete the commit history details.

https://github.com/clyde0813/Interpark-Ticketing/blob/main/captcha%20saver.py

**Comment by clyde0813** [comment]
Thank you for pointing out the mistake. This project was created when I first started programming. At that time, I didn't know how to use Git Hub, so I think I made a mistake. I have initialized all currently problematic commitments. Thanks once again.
